version: '3.6'

services:

  db:
    image: fresh/db
    hostname: db.HOSTNAMEREPLACE
    container_name: db.HOSTNAMEREPLACE
    volumes:
      - ./artifact/db/data:/var/lib/1c/pgdata
      - ./mnt:/mnt
  
  nginx:
    image: fresh/nginx
    hostname: nginx.HOSTNAMEREPLACE
    container_name: nginx.HOSTNAMEREPLACE
    networks: 
      default:
        aliases:
          - HOSTNAMEREPLACE
    environment:
      - SITE_HOST=site.HOSTNAMEREPLACE
      - BACKEND_HOST=web.HOSTNAMEREPLACE
      - GATE_HOST=gate.HOSTNAMEREPLACE
      - HOSTNAME=HOSTNAMEREPLACE
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx_conf/1c_app.conf:/etc/nginx/1c_app.conf
      - ./nginx_conf/1c_common.conf:/etc/nginx/1c_common.conf
      - ./nginx_conf/1c_error.conf:/etc/nginx/1c_error.conf
      - ./nginx_conf/1c_error_openid.conf:/etc/nginx/1c_error_openid.conf
      - ./nginx_conf/1c_error_site.conf:/etc/nginx/1c_error_site.conf
      - ./nginx_conf/1c_keepalive.conf:/etc/nginx/1c_keepalive.conf
      - ./nginx_conf/1c_upstream.conf:/etc/nginx/1c_upstream.conf
      - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_conf/conf.d/local-ssl.conf:/etc/nginx/conf.d/local-ssl.conf
      - ./nginx_conf/conf.d/local.conf://etc/nginx/conf.d/local.conf
      - ./mnt:/mnt
      - ../certs/fullchain.pem:/etc/pki-custom/fullchain.crt
      - ../certs/privkey.pem:/etc/pki-custom/privkey.key
      - ../images/site/distr/site/media:/var/www/content/media/
    depends_on:
      - site
      - forum

  srv:
    image: fresh/core
    hostname: srv.HOSTNAMEREPLACE
    container_name: srv.HOSTNAMEREPLACE
    command: srv+cli
    volumes:
      - ./artifact/srv/data:/var/lib/1c/data
      - ./artifact/srv/log:/var/log/1c
      - ./mnt:/mnt
      - /tmp/.aksusb:/tmp/.aksusb
      - ../licenses_1c:/var/1C/licenses
      - ../images/core/conf/logcfg.xml:/opt/1C/v8.3/x86_64/conf/logcfg.xml
      
    ports:
      - 1540-1541:1540-1541
      - 1538:1538
      - 1550:1550
      - 1560-1591:1560-1591
      - 5900:5900
    depends_on:
      - db

  ras:
    image: fresh/core
    hostname: ras.HOSTNAMEREPLACE
    container_name: ras.HOSTNAMEREPLACE
    command: /opt/1C/v8.3/x86_64/ras cluster --port=1545 srv:1540
    volumes:
      - ./artifact/ras/log:/var/log/1c
      - ./mnt:/mnt
      - ../images/core/conf/logcfg.xml:/opt/1C/v8.3/x86_64/conf/logcfg.xml
    ports:
      - 1545:1545
      
  web:
    image: fresh/core
    hostname: web.HOSTNAMEREPLACE
    container_name: web.HOSTNAMEREPLACE
    command: web
    volumes:
      - ./artifact/web/log:/var/log/1c
      - ./mnt:/mnt
    depends_on:
      - srv
  
  site:
    image: fresh/site
    hostname: site.HOSTNAMEREPLACE
    container_name: site.HOSTNAMEREPLACE
    volumes:
      - ./artifact/site/searchIndex:/var/www/content/searchIndex
      - ./artifact/site/site_files:/var/www/content/site_files
      - ./mnt:/mnt
      - ../distr/postgresql.jar:/usr/local/tomcat/lib/postgresql.jdbc4.jar
      - ../images/site/conf/context.xml:/usr/local/tomcat/conf/context.xml
      - ../images/site/conf/server.xml:/usr/local/tomcat/conf/server.xml
      - ../images/site/distr/site/media:/var/www/content/media/
    depends_on:
      - db

  forum:
    image: fresh/forum
    hostname: forum.HOSTNAMEREPLACE
    container_name: forum.HOSTNAMEREPLACE
    volumes:
      - ./artifact/forum:/var/www/forum/mess_files
      - ./mnt:/mnt
      - ../distr/postgresql.jar:/usr/local/tomcat/lib/postgresql.jdbc4.jar
      - ../images/forum/conf/context.xml:/usr/local/tomcat/conf/context.xml
      - ../images/forum/conf/server.xml:/usr/local/tomcat/conf/server.xml
    depends_on:
      - db

  gate:
    image: fresh/gate
    hostname: gate.HOSTNAMEREPLACE
    container_name: gate.HOSTNAMEREPLACE
    volumes: 
      - ./mnt:/mnt
    depends_on:
      - srv